version: '3.8'

services:
  # api:
  #   build:
  #     context: .
  #     target: development
  #   container_name: emre-case-api
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DB_HOST=postgres
  #     - DB_PORT=5432
  #     - DB_USERNAME=postgres
  #     - DB_PASSWORD=postgres
  #     - DB_DATABASE=emre_case
  #     - JWT_SECRET=your-secret-key
  #     - JWT_REFRESH_SECRET=refresh-secret-key
  #     - PORT=3000
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   command: npm run start:dev
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  postgres:
    image: postgres:14
    container_name: emre-case-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: emre_case
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
